---
- hosts: server3
  become: yes
  handlers:
    - name: restart service
      service:
        name: httpd
        state: restarted
      listen: "restart service"
  tasks:
    - name: installing httpd
      yum: 
        name: httpd
        state: present
    - name: adding content to config file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: adding content to default file
      lineinfile:
        path: /var/www/html/index.html
        line: "last one"
      notify: "restart service"
    - name: getting URL output to page
      get_url:
        url: "http://{{ item }}/index.html"
        dest: "/home/ansible/{{ item }}"
      ignore_errors: yes
      with_items:
        - 172.31.31.19
        - 54.186.129.12
        - 54.212.175.73
    
