---
- hosts: local
  become: yes
  tasks:
    - name: creating users
      file:
        path: "{{ item }}"
        state: touch
      with_items:
        - /home/jithu1/new.txt
        - /home/jithu2/new1.txt

