---
- hosts: server3
  become: yes
  tasks:
   - name: installing httpd
     yum:
       name: httpd
       state: present
   - name: enabling httpd
     service:
       name: httpd
       state: started
       enabled: yes
   - name: placing file on servers
     file:
       path: /var/www/html/index.html
       state: touch
   - name: adding line into file
     lineinfile:
       path: /var/www/html/index.html
       line: "All the best for your trials"

