---
- hosts: local
  become: yes
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
      listen: "restart httpd"
  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: present
      notify: "restart httpd"
          
